# Generated by Django 3.2 on 2022-03-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets')),
            ],
            options={
                'verbose_name': '组件',
                'verbose_name_plural': '组件',
                'db_table': 'components',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='assets/inputimage'),
        ),
    ]
