name: RM2Doc Package Deployment Release

on: [push]
env:
  version: 1.0.0
  
jobs:

  RM2Doc-Package:
    name: RM2Doc Compile and Package
    # if: github.event.pull_request.merged
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        architecture: x64
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Staging
      run: |
        mkdir -p staging
        cp -r com.rm2pt.generator.rm2doc.updatesite/target/*.zip staging

    - uses: actions/upload-artifact@v1
      if: true
      with:
        name: RM2Doc-UpdateSite
        path: staging/com.rm2pt.generator.rm2doc.updatesite-${{ env.version }}-SNAPSHOT.zip         
          
        
  Deployment-Release:
    name: Deploy Release
    needs: RM2Doc-Package
    # if: github.event.pull_request.merged
    if: true
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Checkout code
        # uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN  }} # This token is provided by Actions, you do not need to create your own token
        with:
          owner: RM2PT
          repo: RM2Doc-UpdateSite
          tag_name: v${{ env.version }}
          release_name: RM2Doc Release v${{ env.version }}
          commitish: master
          body: |
            RM2Doc, which includes features as follows:
            - Generate NL Contracts
            - Generate SRS
          draft: true
          prerelease: false
            
      - name: Download UpdateSite
        uses: actions/download-artifact@v1
        with:
           name: RM2Doc-UpdateSite
           path: Release
         
      # - uses: geekyeggo/delete-artifact@v1
      #   with:
      #      name: RM2Doc-UpdateSite    

      - name: Upload UpdateSite Release
        id: upload-release-updatesite
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_name: com.rm2pt.generator.rm2doc.updatesite-${{ env.version }}-SNAPSHOT.zip
          asset_path: Release/com.rm2pt.generator.rm2doc.updatesite-${{ env.version }}-SNAPSHOT.zip
          asset_content_type: application/zip
  Deployment-UpdateSite:
    name: Deploy UpdateSite
    # if: github.event.pull_request.merged
    if: true
    needs: RM2Doc-Package
    runs-on: ubuntu-18.04
    
    steps:
    - name: Download RM2PT-Linux
      uses: actions/download-artifact@v1
      with:
         name: RM2Doc-UpdateSite         
         
      
    - name: Unzip UpdateSite 
      run: |
        cd RM2Doc-UpdateSite
        unzip com.rm2pt.generator.rm2doc.updatesite-${{ env.version }}-SNAPSHOT.zip
        rm -rf com.rm2pt.generator.rm2doc.updatesite-${{ env.version }}-SNAPSHOT.zip
   
    # Runs a set of commands using the runners 
    - name: Add and Commit for UpdateSite
      run: |
          cd RM2Doc-UpdateSite
          echo "This is RM2Doc update site. Please install or update RM2PT through http://rm2pt.com/RM2Doc-UpdateSite" > index.html
          git init
          git add .
          git config --local user.email "CI@rm2pt.com"
          git config --local user.name "RM2PT CI"
          git commit -m "$deploy v${{ env.version }} updatesite"
    - name: Push UpdateSite
      run: |
          cd RM2Doc-UpdateSite
          git remote add origin https://Tians996:${{secrets.PUSH_TOKEN}}@github.com/RM2PT/rm2doc-updatesite.git     
          git push -f origin master
    - name: Delete UpdateSite 
      uses: geekyeggo/delete-artifact@v1
      with:
         name: RM2Doc-UpdateSite
